FROM node:lts AS cli

RUN npm install -g yarn

WORKDIR /home/node
COPY ./packages/cli .
RUN chown -R node /home/node && chmod -R 755 /home/node && chmod 777 /home/node
USER node
RUN yarn
RUN yarn test


FROM node:lts AS schematics

RUN npm install -g yarn

WORKDIR /home/node
RUN rm -rf /home/node/*
COPY ./packages/schematics .
RUN chown -R node /home/node && chmod -R 755 /home/node && chmod 777 /home/node
USER node
RUN yarn
RUN yarn test

