:toc: macro

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

=== Devon4j schematic arguments

When you execute the `cicdgen generate devon4j` command you can also add some arguments in order to modify the behaviour of the command. Those arguments are:

* --docker
+
The type of this paramter if boolean. If it is present, docker related files and pipeline stage will be also generated. For more details see <<./devon4j-files.asciidoc#jenkinsfile-docker,docker section of Jenkinsfile>> and link:./devon4j-docker-files.asciidoc[files generated for docker]

* --plurl
+
Url of Production Line. It is required when `--docker` is true, and it will be used to know where the docker image will be uploaded.

* --openshift
+
The type of this paramter if boolean. If it is present, OpenShift related files and pipeline stage will be also generated. For more details see <<devon4j-files.asciidoc#jenkinsfile-openshift,OpenShift section of Jenkinsfile>> and link:./devon4j-docker-files.asciidoc[files generated for OpenShift] (same as `--docker`)

* --ocurl
+
OpenShift cluster url where the application will be builded and deployed.

* --ocn
+
Openshift cluster namespace

* --teams
+
With this argument we can add the teams notification option in the link:devon4j-files.asciidoc#jenkinsfile-teams[Jenkinsfile].

* --teamsname
+
The name of the Microsft Teams webhook. It is defined at Microsoft Teams connectors.

* --teamsurl
+
The url of the Microsft Teams webhook. It is returned by Microsoft Teams when you create a connector.