pipeline{
    agent any

    options {
        buildDiscarder(logRotator(artifactDaysToKeepStr: '1', artifactNumToKeepStr: '1', daysToKeepStr: '5', numToKeepStr: '50'))
        // Disable concurrent builds. It will wait until the pipeline finish before start a new one
        disableConcurrentBuilds()<% if (teams) { %>
        office365ConnectorWebhooks([[name: '<%= teamsname %>', notifyAborted: true, notifyBackToNormal: true, notifyFailure: true, notifySuccess: true, notifyUnstable: true, url: '<%= teamsurl %>']])<% } %>
    }

    tools {
        jdk 'OpenJDK11'
        <% if (openshift) { %>
        oc "OpenShiftv3.11.0"
        <% } %>
    }

    environment {
        // sonarQube
        // Name of the sonarQube environment
        sonarEnv = "SonarQube"

        // Nexus 3
        // Maven global settings configuration ID
        globalSettingsId = 'MavenSettings'
        // Maven tool id
        mavenInstallation = 'Maven3'

        <% if (docker || openshift) { %>
        // Docker
        dockerFileName = 'Dockerfile.ci'
        dockerRegistry = '<%= registryurl %>'
        dockerRegistryCredentials = 'nexus-api'
        <% } %>
        <% if (docker) { %>
        dockerDaemonUrl = '<%= dockerurl %>'
        dockerCertificateId = '<%= dockercertid %>'
        dockerRegistryProtocol = 'https://'
        containerName = 'java_application'
        dockerTool = 'docker-global'
        <% } %>

        <% if (openshift) { %>
        // Openshift
        openshiftClusterName = '<%= ocname %>'
        timeToCheckApp = 5
        <% } %>
    }

    stages {
        stage ('Loading Custom Tools') {
            when {
               anyOf {
                   branch 'master'
                   branch 'develop'
                   branch 'release/*'
                   branch 'feature/*'
                   branch 'hotfix/*'
                   changeRequest()
               }
            }
            steps {
                <% if (docker) { %>
                tool dockerTool
                <% } %>
                script {
                    def pom = readMavenPom file: './pom.xml';
                    version = pom.version

                    if (env.BRANCH_NAME.startsWith('release')) {
                        dockerTag = "release"
                        deployEnvironment = "-uat"
                        sonarProjectKey = "-release"
                        
                        if (!version.endsWith("-RC")) {
                            version = "${version}-RC"
                        }
                    }

                    if (env.BRANCH_NAME == 'develop') {
                        dockerTag = "latest"
                        deployEnvironment = "-dev"
                        sonarProjectKey = "-develop"

                        if (!version.endsWith("-SNAPSHOT")) {
                            version = "${version}-SNAPSHOT"
                        }
                    }

                    if (env.BRANCH_NAME == 'master') {
                        dockerTag = "production"
                        deployEnvironment = "-stage"
                        sonarProjectKey = ""

                        if (env.BRANCH_NAME == 'master' && (version.endsWith("-RC") || version.endsWith("-SNAPSHOT"))){
                            version = version.replace("-RC", "")
                            version = version.replace("-SNAPSHOT", "")
                        }
                    }

                    // Put the correct version at pom.
                    pom.version = version
                    writeMavenPom model: pom, file: 'pom.xml'

                    def apiPom = readMavenPom file: 'api/pom.xml'
                    apiPom.parent.version = version
                    writeMavenPom model: apiPom, file: 'api/pom.xml'

                    def corePom = readMavenPom file: 'core/pom.xml'
                    corePom.parent.version = version
                    writeMavenPom model: corePom, file: 'core/pom.xml'

                    def serverPom = readMavenPom file: 'server/pom.xml'
                    serverPom.parent.version = version
                    writeMavenPom model: serverPom, file: 'server/pom.xml'
                }
            }
        }

        stage ('Fresh Dependency Installation') {
            when {
               anyOf {
                   branch 'master'
                   branch 'develop'
                   branch 'release/*'
                   branch 'feature/*'
                   branch 'hotfix/*'
                   changeRequest()
               }
            }
            steps {
                withMaven(globalMavenSettingsConfig: globalSettingsId, maven: mavenInstallation) {
                    sh "mvn clean install -Dmaven.test.skip=true"
                }
            }
        }

        stage ('Unit Tests') {
            when {
               anyOf {
                   branch 'master'
                   branch 'develop'
                   branch 'release/*'
                   branch 'feature/*'
                   branch 'hotfix/*'
                   changeRequest()
               }
            }
            steps {
                withMaven(globalMavenSettingsConfig: globalSettingsId, maven: mavenInstallation) {
                    sh "mvn clean test"
                }
            }
        }

        stage ('SonarQube code analysis') {
            when {
               anyOf {
                   branch 'master'
                   branch 'develop'
                   branch 'release/*'
               }
            }
            steps {
                script {
                    withMaven(globalMavenSettingsConfig: globalSettingsId, maven: mavenInstallation) {
                        withSonarQubeEnv(sonarEnv) {
                            // Change the project name (in order to simulate branches with the free version)
                            sh "cp pom.xml pom.xml.bak"
                            sh "cp api/pom.xml api/pom.xml.bak"
                            sh "cp core/pom.xml core/pom.xml.bak"
                            sh "cp server/pom.xml server/pom.xml.bak"

                            def pom = readMavenPom file: './pom.xml';
                            pom.artifactId = "${pom.artifactId}${sonarProjectKey}"
                            writeMavenPom model: pom, file: 'pom.xml'

                            def apiPom = readMavenPom file: 'api/pom.xml'
                            apiPom.parent.artifactId = pom.artifactId
                            apiPom.artifactId = "${pom.artifactId}-api"
                            writeMavenPom model: apiPom, file: 'api/pom.xml'

                            def corePom = readMavenPom file: 'core/pom.xml'
                            corePom.parent.artifactId = pom.artifactId
                            corePom.artifactId = "${pom.artifactId}-core"
                            writeMavenPom model: corePom, file: 'core/pom.xml'

                            def serverPom = readMavenPom file: 'server/pom.xml'
                            serverPom.parent.artifactId = pom.artifactId
                            serverPom.artifactId = "${pom.artifactId}-server"
                            writeMavenPom model: serverPom, file: 'server/pom.xml'

                            sh "mvn sonar:sonar"

                            sh "mv pom.xml.bak pom.xml"
                            sh "mv api/pom.xml.bak api/pom.xml"
                            sh "mv core/pom.xml.bak core/pom.xml"
                            sh "mv server/pom.xml.bak server/pom.xml"
                        }
                    }
                    timeout(time: 1, unit: 'HOURS') {
                        def qg = waitForQualityGate() 
                        if (qg.status != 'OK') {
                            error "Pipeline aborted due to quality gate failure: ${qg.status}"
                        }
                    }
                }
            }
        }
        
        stage ('Deliver application into Nexus') {
            when {
               anyOf {
                   branch 'master'
                   branch 'develop'
                   branch 'release/*'
               }
            }
            steps {
                withMaven(globalMavenSettingsConfig: globalSettingsId, maven: mavenInstallation) {
                    sh "mvn deploy -Dmaven.test.skip=true"
                    sh """
                        cp ${dockerFileName} server/target/Dockerfile
                    """
                }
            }
        }

        <% if (docker) { %>
        stage ('Create the Docker image') {
            when {
                anyOf {
                    branch 'master'
                    branch 'develop'
                    branch 'release/*'
                }
            }
            steps{
                script {
                    def pom = readMavenPom file: 'pom.xml'
                    dir('server/target') {
                        docker.withServer(dockerDaemonUrl<% if(dockercertid){ %>, dockerCertificateId <%}%>) {
                            docker.withRegistry("""${dockerRegistryProtocol}${dockerRegistry}""", dockerRegistryCredentials) {
                                def customImage = docker.build("${pom.artifactId}:${pom.version}")
                                customImage.push()
                                customImage.push(dockerTag);
                            }
                        }
                    }
                }
            }
        }

        stage ('Deploy the new image') {
            when {
                anyOf {
                    branch 'master'
                    branch 'develop'
                    branch 'release/*'
                }
            }
            steps{
                script {
                    docker.withServer(dockerDaemonUrl<% if(dockercertid){ %>, dockerCertificateId <%}%>) {
                        docker.withRegistry("""${dockerRegistryProtocol}${dockerRegistry}""", dockerRegistryCredentials) {
                            def pom = readMavenPom file: 'pom.xml'
                            // Create the docker network
                            def dockerNetworkName = pom.artifactId.split('-')[0].trim()
                            def network = sh returnStdout: true, script: """docker network ls -f name="^${dockerNetworkName}${deployEnvironment}\$" | sed '2q;d' """
                            if (network?.trim() == '') {
                                sh "docker network create ${dockerNetworkName}${deployEnvironment}"
                            } else {
                                println "${dockerNetworkName}${deployEnvironment} network already exists"
                            }
                            // Deploy the docker container
                            docker.image("${dockerRegistry}/${pom.artifactId}:${dockerTag}").pull()

                            def containerId = sh returnStdout: true, script: """docker ps -aqf network=${dockerNetworkName}${deployEnvironment} -f "ancestor=${dockerRegistry}/${pom.artifactId}:${dockerTag}" """
                            if (containerId?.trim()) {
                                sh "docker rm -f ${containerId.trim()}"
                            }

                            println """docker run -d --restart unless-stopped --network=${dockerNetworkName}${deployEnvironment} --network-alias=${containerName} ${dockerRegistry}/${pom.artifactId}:${dockerTag}"""
                            sh """docker run -d --restart unless-stopped --network=${dockerNetworkName}${deployEnvironment} --network-alias=${containerName} ${dockerRegistry}/${pom.artifactId}:${dockerTag}"""
                        }
                    }
                }
            }
        }
        <% } %>

        <% if (openshift) { %>
        stage ('Create the Docker image') {
            when {
                anyOf {
                    branch 'master'
                    branch 'develop'
                    branch 'release/*'

                }
            }
            steps {
                script {
                    def pom = readMavenPom file: 'pom.xml'
                    def appName = "${pom.artifactId}${deployEnvironment}"
                    dir('server/target') {
                        openshift.withCluster(openshiftClusterName){
                            openshift.withProject() {
                                try {
                                    openshift.startBuild("${appName} --from-dir=. --wait") 
                                } catch (e) {
                                    def latestBuildVersion = openshift.selector('bc',"${appName}").object().status.lastVersion
                                    def buildName = "${appName}-${latestBuildVersion}"

                                    echo "Checking ${buildName} build"
                                    def build
                                    def status
                                    try {
                                        build = openshift.selector("build ${buildName}")
                                        status = build.object().status.phase
                                    }catch (eLog) {
                                        error ("[ERROR] - build or status not exist.\n" + e)
                                    }

                                    try {
                                        sh "echo logs for ${build.name()}:"
                                        build.logs()
                                    } catch (eLog) {
                                        sh "echo error reading logs"
                                    }

                                    if (!status) {
                                        error ("" + e)
                                    } else if (status == "Failed") {
                                        error("[FAILED] - The build is not complete, status: " + status + ".\n" + e)
                                    } else if (status) {
                                        error("[TIMEOUT] - The build is not complete, status: " + status + ".\n" + e)
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        stage ('Deploy the new image') {
            when {
                anyOf {
                    branch 'master'
                    branch 'develop'
                    branch 'release/*'
                }
            }
            steps{
                script {
                    def pom = readMavenPom file: 'pom.xml'
                    openshift.withCluster(openshiftClusterName){
                        openshift.withProject() {
                            openshift.raw("import-image ${pom.artifactId}${deployEnvironment}:${dockerTag}")
                        }
                    }
                }
            }
        }

        stage ('Check pod status') {
            when {
                anyOf {
                    branch 'master'
                    branch 'develop'
                    branch 'release/*'
                }
            }
            steps{
                script {
                    def pom = readMavenPom file: 'pom.xml'
                    def appName = "${pom.artifactId}${deployEnvironment}"
                    openshift.withCluster(openshiftClusterName){
                        openshift.withProject() {
                            def latestDeploymentVersion = openshift.selector('dc',"${appName}").object().status.latestVersion
                            def deployment = "${appName}-${latestDeploymentVersion}"

                            echo "Checking ${deployment} pod"
                            def pod = openshift.selector('pod', [deployment: "${deployment}"])
                            def status
                            try {
                                timeout(5) {
                                    pod.untilEach(1) {
                                        status = it.object().status.phase
                                        echo "status of pod: ${status}"
                                        return (status == "Running" || status == "Failed" || status == "Error" || status == "CrashLoopBackOff")
                                    }
                                }
                                if (status != "Running") {
                                    error("")
                                }
                                status = ''
                                try {
                                    timeout(timeToCheckApp) {
                                        pod.untilEach(1) {
                                            getPod = openshift.raw("get ${it.name()}")
                                            sh """echo "${getPod.actions[0].out}" > out"""
                                            status = sh (
                                                script: "sed 's/[\t ][\t ]*/ /g' < out | sed '2q;d' | cut -d' ' -f3",
                                                returnStdout: true
                                            ).trim()
                                            return (status == "Failed" || status == "Error" || status == "CrashLoopBackOff")
                                        }
                                    }
                                    error("")
                                } catch (checked) {
                                    if (status == "Running") {
                                        sh "echo Checked: pod running during ${timeToCheckApp} minutes."
                                    } else {
                                        error("")
                                    }
                                }
                            } catch (e) {
                                try {
                                    sh "echo logs for ${pod.name()}:"
                                    pod.logs()
                                } catch (eLog) {
                                    sh "echo error reading logs"
                                }
                                if (!status) {
                                    error ("" + e)
                                } else if (status == "Failed" || status == "Error" || status == "CrashLoopBackOff") {
                                    error("[FAILED] - The pod is not running, status: " + status + ".\n" + e)
                                } else {
                                    error("[TIMEOUT] - The pod is not running, status: " + status + ".\n" + e)
                                }
                            }
                        }
                    }
                }
            }
        }
        <% } %>
    }

    post {
        cleanup {
            cleanWs()
        }
    }
}
